dsn=https://1837cbfcf3ac4f03a67ec2ba8b91c046@bugsink.august.games/1
release=237.20260615+787dc83
in-app-includes=net.runelite,osrs,custom
attach-stacktrace=true
max-breadcrumbs=250
context-tags=pluginhub_plugin,pluginhub_plugin_name,pluginhub_plugin_version
