runelite.title=August RSPS
runelite.version=237.20260615
runelite.commit=787dc83
runelite.dirty=false
runelite.discord.enable=true
runelite.discord.appid=1058651891589992468
runelite.discord.invite=https://discord.gg/augustrsps
runelite.github.link=https://github.com/runelite/runelite/discussions
runelite.wiki.link=https://github.com/runelite/runelite/wiki
runelite.patreon.link=https://www.patreon.com/runelite
runelite.wiki.troubleshooting.link=https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client
runelite.wiki.building.link=https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA#client-failing-to-start
runelite.dnschange.link=https://1.1.1.1/dns/#setup-instructions
runelite.jav_config=https://github.com/August-Games/august-static/raw/main/august_jav_config_237.ws
runelite.jav_config_backup=https://august-rsps.com/assets/august_jav_config_237.ws
runelite.pluginhub.url=https://dbgugmwkr0ceg.cloudfront.net/pluginhub-rev237
runelite.pluginhub.version=1.12.22.1
runelite.api.base=https://api.runelite.net/runelite-237.20260615
runelite.session=https://api.runelite.net/session
runelite.static.base=https://static.runelite.net
runelite.ws=https://api.runelite.net/ws2
runelite.config=https://static.runelite.net/config.json
runelite.osrstwitter.link=https://twitter.com/OldSchoolRS
runelite.oauth.redirect=https://runelite.net/logged-in
runelite.jagex.domainblock=.discord.com,.runescape.wiki