package net.runelite.client.plugins.itemidentification;

import com.google.common.collect.ImmutableMap;
import java.util.Map;
import java.util.function.Predicate;

enum ItemIdentification {
   GUAM_SEED(ItemIdentification.Type.SEED_HERB, "Guam", "G", new int[]{5291}),
   MARRENTILL_SEED(ItemIdentification.Type.SEED_HERB, "Marren", "M", new int[]{5292}),
   TARROMIN_SEED(ItemIdentification.Type.SEED_HERB, "Tarro", "TAR", new int[]{5293}),
   HARRALANDER_SEED(ItemIdentification.Type.SEED_HERB, "Harra", "HAR", new int[]{5294}),
   RANARR_SEED(ItemIdentification.Type.SEED_HERB, "Ranarr", "R", new int[]{5295}),
   TOADFLAX_SEED(ItemIdentification.Type.SEED_HERB, "Toad", "TOA", new int[]{5296}),
   IRIT_SEED(ItemIdentification.Type.SEED_HERB, "Irit", "I", new int[]{5297}),
   AVANTOE_SEED(ItemIdentification.Type.SEED_HERB, "Avan", "A", new int[]{5298}),
   KWUARM_SEED(ItemIdentification.Type.SEED_HERB, "Kwuarm", "K", new int[]{5299}),
   SNAPDRAGON_SEED(ItemIdentification.Type.SEED_HERB, "Snap", "S", new int[]{5300}),
   CADANTINE_SEED(ItemIdentification.Type.SEED_HERB, "Cadan", "C", new int[]{5301}),
   LANTADYME_SEED(ItemIdentification.Type.SEED_HERB, "Lanta", "L", new int[]{5302}),
   DWARF_WEED_SEED(ItemIdentification.Type.SEED_HERB, "Dwarf", "D", new int[]{5303}),
   TORSTOL_SEED(ItemIdentification.Type.SEED_HERB, "Torstol", "TOR", new int[]{5304}),
   HUASCA_SEED(ItemIdentification.Type.SEED_HERB, "Huasca", "HUA", new int[]{30088}),
   REDBERRY_SEED(ItemIdentification.Type.SEED_BERRY, "Redberry", "RED", new int[]{5101}),
   CADAVABERRY_SEED(ItemIdentification.Type.SEED_BERRY, "Cadava", "CAD", new int[]{5102}),
   DWELLBERRY_SEED(ItemIdentification.Type.SEED_BERRY, "Dwell", "DWEL", new int[]{5103}),
   JANGERBERRY_SEED(ItemIdentification.Type.SEED_BERRY, "Janger", "JANG", new int[]{5104}),
   WHITEBERRY_SEED(ItemIdentification.Type.SEED_BERRY, "White", "WHIT", new int[]{5105}),
   POISON_IVY_SEED(ItemIdentification.Type.SEED_BERRY, "Ivy", "POI", new int[]{5106}),
   GRAPE_SEED(ItemIdentification.Type.SEED_SPECIAL, "Grape", "GRA", new int[]{13657}),
   MUSHROOM_SPORE(ItemIdentification.Type.SEED_SPECIAL, "Mushroom", "MUSH", new int[]{5282}),
   BELLADONNA_SEED(ItemIdentification.Type.SEED_SPECIAL, "Bella", "BELL", new int[]{5281}),
   SEAWEED_SPORE(ItemIdentification.Type.SEED_SPECIAL, "Seaweed", "SW", new int[]{21490}),
   HESPORI_SEED(ItemIdentification.Type.SEED_SPECIAL, "Hespori", "HES", new int[]{22875}),
   KRONOS_SEED(ItemIdentification.Type.SEED_SPECIAL, "Kronos", "KRO", new int[]{22885}),
   IASOR_SEED(ItemIdentification.Type.SEED_SPECIAL, "Iasor", "IA", new int[]{22883}),
   ATTAS_SEED(ItemIdentification.Type.SEED_SPECIAL, "Attas", "AT", new int[]{22881}),
   CACTUS_SEED(ItemIdentification.Type.SEED_SPECIAL, "Cactus", "CAC", new int[]{5280}),
   POTATO_CACTUS_SEED(ItemIdentification.Type.SEED_SPECIAL, "P.Cact", "P.CAC", new int[]{22873}),
   ACORN(ItemIdentification.Type.SEED_TREE, "Oak", "OAK", new int[]{5312}),
   WILLOW_SEED(ItemIdentification.Type.SEED_TREE, "Willow", "WIL", new int[]{5313}),
   MAPLE_SEED(ItemIdentification.Type.SEED_TREE, "Maple", "MAP", new int[]{5314}),
   YEW_SEED(ItemIdentification.Type.SEED_TREE, "Yew", "YEW", new int[]{5315}),
   MAGIC_SEED(ItemIdentification.Type.SEED_TREE, "Magic", "MAG", new int[]{5316}),
   REDWOOD_SEED(ItemIdentification.Type.SEED_TREE, "Red", "RED", new int[]{22871}),
   TEAK_SEED(ItemIdentification.Type.SEED_TREE, "Teak", "TEAK", new int[]{21486}),
   MAHOGANY_SEED(ItemIdentification.Type.SEED_TREE, "Mahog", "MAH", new int[]{21488}),
   CAMPHOR_SEED(ItemIdentification.Type.SEED_TREE, "Camphor", "CAM", new int[]{31547}),
   IRONWOOD_SEED(ItemIdentification.Type.SEED_TREE, "Iron", "IRON", new int[]{31549}),
   ROSEWOOD_SEED(ItemIdentification.Type.SEED_TREE, "Rose", "ROSE", new int[]{31551}),
   CRYSTAL_ACORN(ItemIdentification.Type.SEED_TREE, "Crystal", "CRY", new int[]{23661}),
   CELASTRUS_SEED(ItemIdentification.Type.SEED_TREE, "Celas", "CEL", new int[]{22869}),
   SPIRIT_SEED(ItemIdentification.Type.SEED_TREE, "Spirit", "SPI", new int[]{5317}),
   CALQUAT_SEED(ItemIdentification.Type.SEED_TREE, "Calquat", "CAL", new int[]{5290}),
   APPLE_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Apple", "APP", new int[]{5283}),
   BANANA_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Banana", "BAN", new int[]{5284}),
   ORANGE_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Orange", "ORA", new int[]{5285}),
   CURRY_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Curry", "CUR", new int[]{5286}),
   PINEAPPLE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Pine.A", "PINE", new int[]{5287}),
   PAPAYA_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Papaya", "PAPA", new int[]{5288}),
   PALM_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Palm", "PALM", new int[]{5289}),
   DRAGONFRIUT_TREE_SEED(ItemIdentification.Type.SEED_FRUIT_TREE, "Dragon", "DRA", new int[]{22877}),
   POTATO_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "Potato", "POT", new int[]{5318}),
   ONION_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "Onion", "ONI", new int[]{5319}),
   CABBAGE_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "Cabbage", "CAB", new int[]{5324}),
   TOMATO_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "Tomato", "TOM", new int[]{5322}),
   SWEETCORN_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "S.Corn", "CORN", new int[]{5320}),
   STRAWBERRY_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "S.Berry", "STRA", new int[]{5323}),
   WATERMELON_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "Melon", "MEL", new int[]{5321}),
   SNAPE_GRASS_SEED(ItemIdentification.Type.SEED_ALLOTMENT, "Snape", "SNA", new int[]{22879}),
   MARIGOLD_SEED(ItemIdentification.Type.SEED_FLOWER, "Marigo", "MARI", new int[]{5096}),
   ROSEMARY_SEED(ItemIdentification.Type.SEED_FLOWER, "Rosemar", "ROSE", new int[]{5097}),
   NASTURTIUM_SEED(ItemIdentification.Type.SEED_FLOWER, "Nastur", "NAS", new int[]{5098}),
   WOAD_SEED(ItemIdentification.Type.SEED_FLOWER, "Woad", "WOAD", new int[]{5099}),
   LIMPWURT_SEED(ItemIdentification.Type.SEED_FLOWER, "Limpwurt", "LIMP", new int[]{5100}),
   WHITE_LILY_SEED(ItemIdentification.Type.SEED_FLOWER, "Lily", "LILY", new int[]{22887}),
   BARLEY_SEED(ItemIdentification.Type.HOPS_SEED, "Barley", "BAR", new int[]{5305}),
   HAMMERSTONE_SEED(ItemIdentification.Type.HOPS_SEED, "Hammer", "HAMM", new int[]{5307}),
   ASGARNIAN_SEED(ItemIdentification.Type.HOPS_SEED, "Asgar", "ASG", new int[]{5308}),
   JUTE_SEED(ItemIdentification.Type.HOPS_SEED, "Jute", "JUTE", new int[]{5306}),
   YANILLIAN_SEED(ItemIdentification.Type.HOPS_SEED, "Yani", "YAN", new int[]{5309}),
   FLAX_SEED(ItemIdentification.Type.HOPS_SEED, "Flax", "FLAX", new int[]{31541}),
   KRANDORIAN_SEED(ItemIdentification.Type.HOPS_SEED, "Krand", "KRA", new int[]{5310}),
   WILDBLOOD_SEED(ItemIdentification.Type.HOPS_SEED, "Wild.B", "WILD", new int[]{5311}),
   HEMP_SEED(ItemIdentification.Type.HOPS_SEED, "Hemp", "HEMP", new int[]{31543}),
   COTTON_SEED(ItemIdentification.Type.HOPS_SEED, "Cotton", "COT", new int[]{31545}),
   ELKHORN_FRAG(ItemIdentification.Type.CORAL_FRAG, "Elk", "ELK", new int[]{31511}),
   PILLAR_FRAG(ItemIdentification.Type.CORAL_FRAG, "Pillar", "PIL", new int[]{31513}),
   UMBRAL_FRAG(ItemIdentification.Type.CORAL_FRAG, "Umbral", "UMB", new int[]{31515}),
   SACK(ItemIdentification.Type.SACK, "Empty", "EMP", new int[]{5418}),
   CABBAGE_SACK(ItemIdentification.Type.SACK, "Cabbage", "CAB", new int[]{5460, 5462, 5464, 5466, 5468, 5470, 5472, 5474, 5476, 5478}),
   ONION_SACK(ItemIdentification.Type.SACK, "Onion", "ONI", new int[]{5440, 5442, 5444, 5446, 5448, 5450, 5452, 5454, 5456, 5458}),
   POTATO_SACK(ItemIdentification.Type.SACK, "Potato", "POT", new int[]{5420, 5422, 5424, 5426, 5428, 5430, 5432, 5434, 5436, 5438}),
   GUAM(ItemIdentification.Type.HERB, "Guam", "G", new int[]{249, 199}),
   MARRENTILL(ItemIdentification.Type.HERB, "Marren", "M", new int[]{251, 201}),
   TARROMIN(ItemIdentification.Type.HERB, "Tarro", "TAR", new int[]{253, 203}),
   HARRALANDER(ItemIdentification.Type.HERB, "Harra", "HAR", new int[]{255, 205}),
   RANARR(ItemIdentification.Type.HERB, "Ranarr", "R", new int[]{257, 207}),
   TOADFLAX(ItemIdentification.Type.HERB, "Toad", "TOA", new int[]{2998, 3049}),
   IRIT(ItemIdentification.Type.HERB, "Irit", "I", new int[]{259, 209}),
   AVANTOE(ItemIdentification.Type.HERB, "Avan", "A", new int[]{261, 211}),
   KWUARM(ItemIdentification.Type.HERB, "Kwuarm", "K", new int[]{263, 213}),
   SNAPDRAGON(ItemIdentification.Type.HERB, "Snap", "S", new int[]{3000, 3051}),
   CADANTINE(ItemIdentification.Type.HERB, "Cadan", "C", new int[]{265, 215}),
   LANTADYME(ItemIdentification.Type.HERB, "Lanta", "L", new int[]{2481, 2485}),
   DWARF_WEED(ItemIdentification.Type.HERB, "Dwarf", "D", new int[]{267, 217}),
   TORSTOL(ItemIdentification.Type.HERB, "Torstol", "TOR", new int[]{269, 219}),
   HUASCA(ItemIdentification.Type.HERB, "Huasca", "HUA", new int[]{30097, 30094}),
   ARDRIGAL(ItemIdentification.Type.HERB, "Ardrig", "ARD", new int[]{1528, 1527}),
   ROGUES_PURSE(ItemIdentification.Type.HERB, "Rogue", "ROG", new int[]{1534, 1533}),
   SITO_FOIL(ItemIdentification.Type.HERB, "Sito", "SF", new int[]{1530, 1529}),
   SNAKE_WEED(ItemIdentification.Type.HERB, "Snake", "SW", new int[]{1526, 1525}),
   VOLENCIA_MOSS(ItemIdentification.Type.HERB, "Volenc", "V", new int[]{1532, 1531}),
   RED_LOGS(ItemIdentification.Type.LOGS, "Red", "RED", new int[]{7404}),
   GREEN_LOGS(ItemIdentification.Type.LOGS, "Green", "GRE", new int[]{7405}),
   BLUE_LOGS(ItemIdentification.Type.LOGS, "Blue", "BLU", new int[]{7406}),
   WHITE_LOGS(ItemIdentification.Type.LOGS, "White", "WHI", new int[]{10328}),
   PURPLE_LOGS(ItemIdentification.Type.LOGS, "Purple", "PUR", new int[]{10329}),
   SCRAPEY_TREE_LOGS(ItemIdentification.Type.LOGS, "Scrapey", "SCRAP", new int[]{8934}),
   LOG(ItemIdentification.Type.LOGS, "Log", "LOG", new int[]{1511}),
   ACHEY_TREE_LOG(ItemIdentification.Type.LOGS, "Achey", "ACH", new int[]{2862}),
   OAK_LOG(ItemIdentification.Type.LOGS, "Oak", "OAK", new int[]{1521}),
   WILLOW_LOG(ItemIdentification.Type.LOGS, "Willow", "WIL", new int[]{1519}),
   TEAK_LOG(ItemIdentification.Type.LOGS, "Teak", "TEAK", new int[]{6333}),
   JATOBA_LOG(ItemIdentification.Type.LOGS, "Jatoba", "JAT", new int[]{32902}),
   JUNIPER_LOG(ItemIdentification.Type.LOGS, "Juniper", "JUN", new int[]{13355}),
   MAPLE_LOG(ItemIdentification.Type.LOGS, "Maple", "MAP", new int[]{1517}),
   MAHOGANY_LOG(ItemIdentification.Type.LOGS, "Mahog", "MAH", new int[]{6332}),
   ARCTIC_PINE_LOG(ItemIdentification.Type.LOGS, "Arctic", "ARC", new int[]{10810}),
   YEW_LOG(ItemIdentification.Type.LOGS, "Yew", "YEW", new int[]{1515}),
   BLISTERWOOD_LOG(ItemIdentification.Type.LOGS, "Blister", "BLI", new int[]{24691}),
   CAMPHOR_LOG(ItemIdentification.Type.LOGS, "Camphor", "CAM", new int[]{32904}),
   MAGIC_LOG(ItemIdentification.Type.LOGS, "Magic", "MAG", new int[]{1513}),
   IRONWOOD_LOG(ItemIdentification.Type.LOGS, "Iron", "IRON", new int[]{32907}),
   REDWOOD_LOG(ItemIdentification.Type.LOGS, "Red", "RED", new int[]{19669}),
   ROSEWOOD_LOG(ItemIdentification.Type.LOGS, "Rose", "ROSE", new int[]{32910}),
   PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Pyre", "P", new int[]{3438}),
   ARCTIC_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Art P", "AP", new int[]{10808}),
   OAK_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Oak P", "OAKP", new int[]{3440}),
   WILLOW_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Wil P", "WILP", new int[]{3442}),
   TEAK_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Teak P", "TEAKP", new int[]{6211}),
   MAPLE_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Map P", "MAPP", new int[]{3444}),
   MAHOGANY_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Mah P", "MAHP", new int[]{6213}),
   YEW_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Yew P", "YEWP", new int[]{3446}),
   CAMPHOR_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Cam P", "CAMP", new int[]{31383}),
   MAGIC_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Mag P", "MAGP", new int[]{3448}),
   IRONWOOD_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Iron P", "IRONP", new int[]{31386}),
   REDWOOD_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Red P", "REDP", new int[]{19672}),
   ROSEWOOD_PYRE_LOGS(ItemIdentification.Type.LOGS_PYRE, "Rose P", "ROSEP", new int[]{31389}),
   WOODEN_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Wooden", "WOOD", new int[]{31964}),
   OAK_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Oak", "OAK", new int[]{31967}),
   TEAK_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Teak", "TEAK", new int[]{31970}),
   MAHOGANY_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Mahog", "MAH", new int[]{31973}),
   CAMPHOR_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Camphor", "CAM", new int[]{31976}),
   IRONWOOD_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Iron", "IRON", new int[]{31979}),
   ROSEWOOD_REPAIR_KIT(ItemIdentification.Type.REPAIR_KIT, "Rose", "ROSE", new int[]{31982}),
   PLANK(ItemIdentification.Type.PLANK, "Plank", "PLANK", new int[]{960}),
   OAK_PLANK(ItemIdentification.Type.PLANK, "Oak", "OAK", new int[]{8778}),
   TEAK_PLANK(ItemIdentification.Type.PLANK, "Teak", "TEAK", new int[]{8780}),
   MAHOGANY_PLANK(ItemIdentification.Type.PLANK, "Mahog", "MAH", new int[]{8782}),
   CAMPHOR_PLANK(ItemIdentification.Type.PLANK, "Camphor", "CAM", new int[]{31432}),
   IRONWOOD_PLANK(ItemIdentification.Type.PLANK, "Iron", "IRON", new int[]{31435}),
   ROSEWOOD_PLANK(ItemIdentification.Type.PLANK, "Rose", "ROSE", new int[]{31438}),
   WAXWOOD_PLANK(ItemIdentification.Type.PLANK, "Wax", "WAX", new int[]{24939}),
   MALLIGNUM_ROOT_PLANK(ItemIdentification.Type.PLANK, "Mallig", "MALL", new int[]{21036}),
   BALL_OF_WOOL(ItemIdentification.Type.YARN, "Wool", "WOOL", new int[]{1759}),
   LINEN_YARN(ItemIdentification.Type.YARN, "Linen", "LIN", new int[]{31463}),
   HEMP_YARN(ItemIdentification.Type.YARN, "Hemp", "HEMP", new int[]{31466}),
   COTTON_YARN(ItemIdentification.Type.YARN, "Cotton", "COT", new int[]{31469}),
   BOLT_OF_CLOTH(ItemIdentification.Type.CLOTH, "Cloth", "CLO", new int[]{8790}),
   BOLT_OF_LINEN(ItemIdentification.Type.CLOTH, "Linen", "LIN", new int[]{31472}),
   BOLT_OF_CANVAS(ItemIdentification.Type.CLOTH, "Canvas", "CAN", new int[]{31475}),
   BOLT_OF_COTTON(ItemIdentification.Type.CLOTH, "Cotton", "COT", new int[]{31478}),
   OAK_SAPLING(ItemIdentification.Type.SAPLING, "Oak", "OAK", new int[]{5370, 5358, 5364}),
   WILLOW_SAPLING(ItemIdentification.Type.SAPLING, "Willow", "WIL", new int[]{5371, 5359, 5365}),
   MAPLE_SAPLING(ItemIdentification.Type.SAPLING, "Maple", "MAP", new int[]{5372, 5360, 5366}),
   YEW_SAPLING(ItemIdentification.Type.SAPLING, "Yew", "YEW", new int[]{5373, 5361, 5367}),
   MAGIC_SAPLING(ItemIdentification.Type.SAPLING, "Magic", "MAG", new int[]{5374, 5362, 5368}),
   REDWOOD_SAPLING(ItemIdentification.Type.SAPLING, "Red", "RED", new int[]{22859, 22850, 22854}),
   SPIRIT_SAPLING(ItemIdentification.Type.SAPLING, "Spirit", "SPI", new int[]{5375, 5363, 5369}),
   CRYSTAL_SAPLING(ItemIdentification.Type.SAPLING, "Crystal", "CRY", new int[]{23659, 23655, 23657}),
   APPLE_SAPLING(ItemIdentification.Type.SAPLING, "Apple", "APP", new int[]{5496, 5480, 5488}),
   BANANA_SAPLING(ItemIdentification.Type.SAPLING, "Banana", "BAN", new int[]{5497, 5481, 5489}),
   ORANGE_SAPLING(ItemIdentification.Type.SAPLING, "Orange", "ORA", new int[]{5498, 5482, 5490}),
   CURRY_SAPLING(ItemIdentification.Type.SAPLING, "Curry", "CUR", new int[]{5499, 5483, 5491}),
   PINEAPPLE_SAPLING(ItemIdentification.Type.SAPLING, "Pine", "PINE", new int[]{5500, 5484, 5492}),
   PAPAYA_SAPLING(ItemIdentification.Type.SAPLING, "Papaya", "PAP", new int[]{5501, 5485, 5493}),
   PALM_SAPLING(ItemIdentification.Type.SAPLING, "Palm", "PALM", new int[]{5502, 5486, 5494}),
   DRAGONFRUIT_SAPLING(ItemIdentification.Type.SAPLING, "Dragon", "DRAG", new int[]{22866, 22862, 22864}),
   TEAK_SAPLING(ItemIdentification.Type.SAPLING, "Teak", "TEAK", new int[]{21477, 21469, 21473}),
   MAHOGANY_SAPLING(ItemIdentification.Type.SAPLING, "Mahog", "MAHOG", new int[]{21480, 21471, 21475}),
   CAMPHOR_SAPLING(ItemIdentification.Type.SAPLING, "Camphor", "CAM", new int[]{31502, 31490, 31496}),
   IRONWOOD_SAPLING(ItemIdentification.Type.SAPLING, "Iron", "IRON", new int[]{31505, 31492, 31498}),
   ROSEWOOD_SAPLING(ItemIdentification.Type.SAPLING, "Rose", "ROSE", new int[]{31508, 31494, 31500}),
   CALQUAT_SAPLING(ItemIdentification.Type.SAPLING, "Calquat", "CALQ", new int[]{5503, 5487, 5495}),
   CELASTRUS_SAPLING(ItemIdentification.Type.SAPLING, "Celas", "CEL", new int[]{22856, 22848, 22852}),
   COMPOST(ItemIdentification.Type.COMPOST, "Compost", "COM", new int[]{6032}),
   SUPERCOMPOST(ItemIdentification.Type.COMPOST, "Sup Com", "SCOM", new int[]{6034}),
   ULTRACOMPOST(ItemIdentification.Type.COMPOST, "Ult Com", "UCOM", new int[]{21483}),
   COPPER_ORE(ItemIdentification.Type.ORE, "Copper", "COP", new int[]{436}),
   TIN_ORE(ItemIdentification.Type.ORE, "Tin", "TIN", new int[]{438}),
   IRON_ORE(ItemIdentification.Type.ORE, "Iron", "IRO", new int[]{440}),
   SILVER_ORE(ItemIdentification.Type.ORE, "Silver", "SIL", new int[]{442}),
   LEAD_ORE(ItemIdentification.Type.ORE, "Lead", "LEA", new int[]{31716}),
   COAL_ORE(ItemIdentification.Type.ORE, "Coal", "COA", new int[]{453}),
   GOLD_ORE(ItemIdentification.Type.ORE, "Gold", "GOL", new int[]{444}),
   MITHRIL_ORE(ItemIdentification.Type.ORE, "Mithril", "MIT", new int[]{447}),
   ADAMANTITE_ORE(ItemIdentification.Type.ORE, "Adaman", "ADA", new int[]{449}),
   NICKEL_ORE(ItemIdentification.Type.ORE, "Nickel", "NIC", new int[]{31719}),
   RUNITE_ORE(ItemIdentification.Type.ORE, "Runite", "RUN", new int[]{451}),
   RUNE_ESSENCE(ItemIdentification.Type.ORE, "R.Ess", "R.E.", new int[]{1436}),
   PURE_ESSENCE(ItemIdentification.Type.ORE, "P.Ess", "P.E.", new int[]{7936}),
   PAYDIRT(ItemIdentification.Type.ORE, "Paydirt", "PAY", new int[]{12011}),
   AMETHYST(ItemIdentification.Type.ORE, "Amethy", "AME", new int[]{21347}),
   LOVAKITE_ORE(ItemIdentification.Type.ORE, "Lovakit", "LOV", new int[]{13356}),
   BLURITE_ORE(ItemIdentification.Type.ORE, "Blurite", "BLU", new int[]{668}),
   ELEMENTAL_ORE(ItemIdentification.Type.ORE, "Element", "ELE", new int[]{2892}),
   DAEYALT_ORE(ItemIdentification.Type.ORE, "Daeyalt", "DAE", new int[]{9632}),
   LUNAR_ORE(ItemIdentification.Type.ORE, "Lunar", "LUN", new int[]{9076}),
   BRONZE_BAR(ItemIdentification.Type.BAR, "Bronze", "BRO", new int[]{2349}),
   IRON_BAR(ItemIdentification.Type.BAR, "Iron", "IRO", new int[]{2351}),
   SILVER_BAR(ItemIdentification.Type.BAR, "Silver", "SIL", new int[]{2355}),
   LEAD_BAR(ItemIdentification.Type.BAR, "Lead", "LEA", new int[]{32889}),
   STEEL_BAR(ItemIdentification.Type.BAR, "Steel", "STE", new int[]{2353}),
   GOLD_BAR(ItemIdentification.Type.BAR, "Gold", "GOL", new int[]{2357}),
   MITHRIL_BAR(ItemIdentification.Type.BAR, "Mithril", "MIT", new int[]{2359}),
   ADAMANTITE_BAR(ItemIdentification.Type.BAR, "Adaman", "ADA", new int[]{2361}),
   CUPRONICKEL_BAR(ItemIdentification.Type.BAR, "Cupro", "CUP", new int[]{32892}),
   RUNITE_BAR(ItemIdentification.Type.BAR, "Runite", "RUN", new int[]{2363}),
   BLURITE_BAR(ItemIdentification.Type.BAR, "Blurite", "BLU", new int[]{9467}),
   ELEMENTAL_METAL(ItemIdentification.Type.BAR, "Elemental", "ELE", new int[]{2893}),
   LOVAKITE_BAR(ItemIdentification.Type.BAR, "Lovakite", "LOV", new int[]{13354}),
   LUNAR_BAR(ItemIdentification.Type.BAR, "Lunar", "LUN", new int[]{9077}),
   SAPPHIRE(ItemIdentification.Type.GEM, "Sapphir", "S", new int[]{1623, 1607}),
   EMERALD(ItemIdentification.Type.GEM, "Emerald", "E", new int[]{1621, 1605}),
   RUBY(ItemIdentification.Type.GEM, "Ruby", "R", new int[]{1619, 1603}),
   DIAMOND(ItemIdentification.Type.GEM, "Diamon", "DI", new int[]{1617, 1601}),
   OPAL(ItemIdentification.Type.GEM, "Opal", "OP", new int[]{1625, 1609}),
   JADE(ItemIdentification.Type.GEM, "Jade", "J", new int[]{1627, 1611}),
   RED_TOPAZ(ItemIdentification.Type.GEM, "Topaz", "T", new int[]{1629, 1613}),
   DRAGONSTONE(ItemIdentification.Type.GEM, "Dragon", "DR", new int[]{1631, 1615}),
   ONYX(ItemIdentification.Type.GEM, "Onyx", "ON", new int[]{6571, 6573}),
   ZENYTE(ItemIdentification.Type.GEM, "Zenyte", "Z", new int[]{19496, 19493}),
   SHADOW_DIAMOND(ItemIdentification.Type.GEM, "Shadow", "SHD", new int[]{4673}),
   BLOOD_DIAMOND(ItemIdentification.Type.GEM, "Blood", "BD", new int[]{4670}),
   ICE_DIAMOND(ItemIdentification.Type.GEM, "Ice", "ID", new int[]{4671}),
   SMOKE_DIAMOND(ItemIdentification.Type.GEM, "Smoke", "SMD", new int[]{4672}),
   ATTACK(ItemIdentification.Type.POTION, "Att", "A", new int[]{2428, 121, 123, 125}),
   ATTACK_MIX(ItemIdentification.Type.POTION, "Att", "A", new int[]{11431, 11429}),
   STRENGTH(ItemIdentification.Type.POTION, "Str", "S", new int[]{113, 115, 117, 119}),
   STRENGTH_MIX(ItemIdentification.Type.POTION, "Str", "S", new int[]{11441, 11443}),
   DEFENCE(ItemIdentification.Type.POTION, "Def", "D", new int[]{2432, 133, 135, 137}),
   DEFENCE_MIX(ItemIdentification.Type.POTION, "Def", "D", new int[]{11459, 11457}),
   COMBAT(ItemIdentification.Type.POTION, "Com", "C", new int[]{9739, 9741, 9743, 9745}),
   COMBAT_MIX(ItemIdentification.Type.POTION, "Com", "C", new int[]{11447, 11445}),
   MAGIC(ItemIdentification.Type.POTION, "Magic", "M", new int[]{3040, 3042, 3044, 3046}),
   MAGIC_MIX(ItemIdentification.Type.POTION, "Magic", "M", new int[]{11515, 11513}),
   RANGING(ItemIdentification.Type.POTION, "Range", "R", new int[]{2444, 169, 171, 173}),
   RANGING_MIX(ItemIdentification.Type.POTION, "Range", "R", new int[]{11511, 11509}),
   BASTION(ItemIdentification.Type.POTION, "Bastion", "B", new int[]{22461, 22464, 22467, 22470}),
   BATTLEMAGE(ItemIdentification.Type.POTION, "BatMage", "B.M", new int[]{22449, 22452, 22455, 22458}),
   SUPER_ATTACK(ItemIdentification.Type.POTION, "S.Att", "S.A", new int[]{2436, 145, 147, 149}),
   SUPER_ATTACK_MIX(ItemIdentification.Type.POTION, "S.Att", "S.A", new int[]{11471, 11469}),
   SUPER_STRENGTH(ItemIdentification.Type.POTION, "S.Str", "S.S", new int[]{2440, 157, 159, 161}),
   SUPER_STRENGTH_MIX(ItemIdentification.Type.POTION, "S.Str", "S.S", new int[]{11487, 11485}),
   SUPER_DEFENCE(ItemIdentification.Type.POTION, "S.Def", "S.D", new int[]{2442, 163, 165, 167}),
   SUPER_DEFENCE_MIX(ItemIdentification.Type.POTION, "S.Def", "S.D", new int[]{11499, 11497}),
   SUPER_COMBAT(ItemIdentification.Type.POTION, "S.Com", "S.C", new int[]{12695, 12697, 12699, 12701}),
   SUPER_RANGING(ItemIdentification.Type.POTION, "S.Range", "S.Ra", new int[]{11722, 11723, 11724, 11725}),
   SUPER_MAGIC(ItemIdentification.Type.POTION, "S.Magic", "S.M", new int[]{11726, 11727, 11728, 11729}),
   DIVINE_SUPER_ATTACK(ItemIdentification.Type.POTION, "S.Att", "S.A", new int[]{23697, 23700, 23703, 23706}),
   DIVINE_SUPER_DEFENCE(ItemIdentification.Type.POTION, "S.Def", "S.D", new int[]{23721, 23724, 23727, 23730}),
   DIVINE_SUPER_STRENGTH(ItemIdentification.Type.POTION, "S.Str", "S.S", new int[]{23709, 23712, 23715, 23718}),
   DIVINE_SUPER_COMBAT(ItemIdentification.Type.POTION, "S.Com", "S.C", new int[]{23685, 23688, 23691, 23694}),
   DIVINE_RANGING(ItemIdentification.Type.POTION, "Range", "R", new int[]{23733, 23736, 23739, 23742}),
   DIVINE_MAGIC(ItemIdentification.Type.POTION, "Magic", "M", new int[]{23745, 23748, 23751, 23754}),
   DIVINE_BASTION(ItemIdentification.Type.POTION, "Bastion", "B", new int[]{24635, 24638, 24641, 24644}),
   DIVINE_BATTLEMAGE(ItemIdentification.Type.POTION, "BatMage", "B.M", new int[]{24623, 24626, 24629, 24632}),
   RESTORE(ItemIdentification.Type.POTION, "Restore", "Re", new int[]{2430, 127, 129, 131}),
   RESTORE_MIX(ItemIdentification.Type.POTION, "Restore", "Re", new int[]{11451, 11449}),
   GUTHIX_BALANCE(ItemIdentification.Type.POTION, "GuthBal", "G.B.", new int[]{7660, 7662, 7664, 7666}),
   SUPER_RESTORE(ItemIdentification.Type.POTION, "S.Rest", "S.Re", new int[]{3024, 3026, 3028, 3030}),
   SUPER_RESTORE_MIX(ItemIdentification.Type.POTION, "S.Rest", "S.Re", new int[]{11495, 11493}),
   PRAYER(ItemIdentification.Type.POTION, "Prayer", "P", new int[]{2434, 139, 141, 143}),
   PRAYER_MIX(ItemIdentification.Type.POTION, "Prayer", "P", new int[]{11467, 11465}),
   ENERGY(ItemIdentification.Type.POTION, "Energy", "En", new int[]{3008, 3010, 3012, 3014}),
   ENERGY_MIX(ItemIdentification.Type.POTION, "Energy", "En", new int[]{11455, 11453}),
   SUPER_ENERGY(ItemIdentification.Type.POTION, "S.Energ", "S.En", new int[]{3016, 3018, 3020, 3022}),
   SUPER_ENERGY_MIX(ItemIdentification.Type.POTION, "S.Energ", "S.En", new int[]{11483, 11481}),
   EXTREME_ENERGY(ItemIdentification.Type.POTION, "E.Energy", "E.En", new int[]{31614, 31617, 31620, 31623}),
   STAMINA(ItemIdentification.Type.POTION, "Stamina", "St", new int[]{12625, 12627, 12629, 12631}),
   EXTENDED_STAMINA(ItemIdentification.Type.POTION, "E.Stamina", "E.St", new int[]{31638, 31641, 31644, 31647}),
   STAMINA_MIX(ItemIdentification.Type.POTION, "Stamina", "Sta", new int[]{12635, 12633}),
   OVERLOAD(ItemIdentification.Type.POTION, "Overloa", "OL", new int[]{11730, 11731, 11732, 11733}),
   ABSORPTION(ItemIdentification.Type.POTION, "Absorb", "Ab", new int[]{11734, 11735, 11736, 11737}),
   BLIGHTED_SUPER_RESTORE(ItemIdentification.Type.POTION, "BS.Rest", "BS.Re", new int[]{24598, 24601, 24603, 24605}),
   PRAYER_REGENERATION(ItemIdentification.Type.POTION, "Pray R.", "P.R.", new int[]{30125, 30128, 30131, 30134}),
   GOADING(ItemIdentification.Type.POTION, "Goading", "G", new int[]{30137, 30140, 30143, 30146}),
   ZAMORAK_BREW(ItemIdentification.Type.POTION, "ZammyBr", "Za", new int[]{2450, 189, 191, 193}),
   ZAMORAK_MIX(ItemIdentification.Type.POTION, "ZammyBr", "Z", new int[]{11523, 11521}),
   SARADOMIN_BREW(ItemIdentification.Type.POTION, "SaraBr", "Sa", new int[]{6685, 6687, 6689, 6691}),
   ANCIENT_BREW(ItemIdentification.Type.POTION, "AncBr", "A.Br", new int[]{26340, 26342, 26344, 26346}),
   ANCIENT_MIX(ItemIdentification.Type.POTION, "AncBr", "Anc", new int[]{26353, 26350}),
   ARMADYL_BREW(ItemIdentification.Type.POTION, "Armadyl", "Arm", new int[]{31650, 31653, 31656, 31659}),
   FORGOTTEN_BREW(ItemIdentification.Type.POTION, "ForgBr", "F.Br", new int[]{27629, 27632, 27635, 27638}),
   SURGE_POTION(ItemIdentification.Type.POTION, "Surge", "Sur", new int[]{30875, 30878, 30881, 30884}),
   ANTIPOISON(ItemIdentification.Type.POTION, "AntiP", "AP", new int[]{2446, 175, 177, 179}),
   ANTIPOISON_MIX(ItemIdentification.Type.POTION, "AntiP", "AP", new int[]{11435, 11433}),
   SUPERANTIPOISON(ItemIdentification.Type.POTION, "S.AntiP", "S.AP", new int[]{2448, 181, 183, 185}),
   ANTIPOISON_SUPERMIX(ItemIdentification.Type.POTION, "S.AntiP", "S.AP", new int[]{11475, 11473}),
   ANTIDOTE_P(ItemIdentification.Type.POTION, "Antid+", "A+", new int[]{5943, 5945, 5947, 5949}),
   ANTIDOTE_P_MIX(ItemIdentification.Type.POTION, "Antid+", "A+", new int[]{11503, 11501}),
   ANTIDOTE_PP(ItemIdentification.Type.POTION, "Antid++", "A++", new int[]{5952, 5954, 5956, 5958}),
   ANTIVENOM(ItemIdentification.Type.POTION, "Anti-V", "AV", new int[]{12905, 12907, 12909, 12911}),
   ANTIVENOM_P(ItemIdentification.Type.POTION, "Anti-V+", "AV+", new int[]{12913, 12915, 12917, 12919}),
   EXT_ANTIVENOM_P(ItemIdentification.Type.POTION, "E.AntiV+", "EAV+", new int[]{29824, 29827, 29830, 29833}),
   RELICYMS_BALM(ItemIdentification.Type.POTION, "Relicym", "R.B", new int[]{4842, 4844, 4846, 4848}),
   RELICYMS_MIX(ItemIdentification.Type.POTION, "Relicym", "R.B", new int[]{11439, 11437}),
   SANFEW_SERUM(ItemIdentification.Type.POTION, "Sanfew", "Sf", new int[]{10925, 10927, 10929, 10931}),
   ANTIFIRE(ItemIdentification.Type.POTION, "Antif", "Af", new int[]{2452, 2454, 2456, 2458}),
   ANTIFIRE_MIX(ItemIdentification.Type.POTION, "Antif", "Af", new int[]{11507, 11505}),
   EXTENDED_ANTIFIRE(ItemIdentification.Type.POTION, "E.Antif", "E.Af", new int[]{11951, 11953, 11955, 11957}),
   EXTENDED_ANTIFIRE_MIX(ItemIdentification.Type.POTION, "E.Antif", "E.Af", new int[]{11962, 11960}),
   SUPER_ANTIFIRE(ItemIdentification.Type.POTION, "S.Antif", "S.Af", new int[]{21978, 21981, 21984, 21987}),
   SUPER_ANTIFIRE_MIX(ItemIdentification.Type.POTION, "S.Antif", "S.Af", new int[]{21997, 21994}),
   EXTENDED_SUPER_ANTIFIRE(ItemIdentification.Type.POTION, "ES.Antif", "ES.Af", new int[]{22209, 22212, 22215, 22218}),
   EXTENDED_SUPER_ANTIFIRE_MIX(ItemIdentification.Type.POTION, "ES.Antif", "ES.Af", new int[]{22224, 22221}),
   SERUM_207(ItemIdentification.Type.POTION, "Ser207", "S7", new int[]{3408, 3410, 3412, 3414}),
   SERUM_208(ItemIdentification.Type.POTION, "Ser208", "S8", new int[]{3416, 3417, 3418, 3419}),
   SACRED_OIL(ItemIdentification.Type.POTION, "SaOil", "SO", new int[]{3430, 3432, 3434, 3436}),
   OLIVE_OIL(ItemIdentification.Type.POTION, "Olive", "Oli", new int[]{3422, 3424, 3426, 3428}),
   COMPOST_POTION(ItemIdentification.Type.POTION, "Compost", "COM", new int[]{6470, 6472, 6474, 6476}),
   AGILITY(ItemIdentification.Type.POTION, "Agility", "Ag", new int[]{3032, 3034, 3036, 3038}),
   AGILITY_MIX(ItemIdentification.Type.POTION, "Agility", "Ag", new int[]{11463, 11461}),
   FISHING(ItemIdentification.Type.POTION, "Fishing", "Fi", new int[]{2438, 151, 153, 155}),
   FISHING_MIX(ItemIdentification.Type.POTION, "Fishing", "Fi", new int[]{11479, 11477}),
   HUNTER(ItemIdentification.Type.POTION, "Hunter", "Hu", new int[]{9998, 10000, 10002, 10004}),
   HUNTING_MIX(ItemIdentification.Type.POTION, "Hunter", "Hu", new int[]{11519, 11517}),
   SUPER_FISHING(ItemIdentification.Type.POTION, "S.Fishing", "S.Fi", new int[]{31602, 31605, 31608, 31611}),
   SUPER_HUNTING(ItemIdentification.Type.POTION, "S.Hunter", "S.Hu", new int[]{31626, 31629, 31632, 31635}),
   GOBLIN(ItemIdentification.Type.POTION, "Goblin", "G", new int[]{26581, 26583, 26585, 26587}),
   MAGIC_ESS(ItemIdentification.Type.POTION, "MagEss", "M.E", new int[]{9021, 9022, 9023, 9024}),
   MAGIC_ESSENCE_MIX(ItemIdentification.Type.POTION, "MagEss", "M.E", new int[]{11491, 11489}),
   REJUVENATION(ItemIdentification.Type.POTION, "Rejuv", "Rj", new int[]{20699, 20700, 20701, 20702}),
   ELDER(ItemIdentification.Type.POTION, "Elder", "El", new int[]{20916, 20915, 20914, 20913, 20920, 20919, 20918, 20917, 20924, 20923, 20922, 20921}),
   TWISTED(ItemIdentification.Type.POTION, "Twisted", "Tw", new int[]{20928, 20927, 20926, 20925, 20932, 20931, 20930, 20929, 20936, 20935, 20934, 20933}),
   KODAI(ItemIdentification.Type.POTION, "Kodai", "Ko", new int[]{20940, 20939, 20938, 20937, 20944, 20943, 20942, 20941, 20948, 20947, 20946, 20945}),
   ANTIPOISON_COX(ItemIdentification.Type.POTION, "AntiP", "AP", new int[]{25757, 25756, 25755, 25754, 25761, 25760, 25759, 25758, 25765, 25764, 25763, 25762}),
   REVITALISATION(ItemIdentification.Type.POTION, "Revit", "Re", new int[]{20952, 20951, 20950, 20949, 20956, 20955, 20954, 20953, 20960, 20959, 20958, 20957}),
   PRAYER_ENHANCE(ItemIdentification.Type.POTION, "P.Enh", "Enh", new int[]{20964, 20963, 20962, 20961, 20968, 20967, 20966, 20965, 20972, 20971, 20970, 20969}),
   XERICS_AID(ItemIdentification.Type.POTION, "X.Aid", "Aid", new int[]{20976, 20975, 20974, 20973, 20980, 20979, 20978, 20977, 20984, 20983, 20982, 20981}),
   OVERLOAD_COX(ItemIdentification.Type.POTION, "Overloa", "Ovl", new int[]{20988, 20987, 20986, 20985, 20992, 20991, 20990, 20989, 20996, 20995, 20994, 20993}),
   NECTAR(ItemIdentification.Type.POTION, "Nectar", "N", new int[]{27315, 27317, 27319, 27321}),
   AMBROSIA(ItemIdentification.Type.POTION, "Ambros", "A", new int[]{27347, 27349}),
   LIQUID_ADRENALINE(ItemIdentification.Type.POTION, "L.Adrn", "L.A", new int[]{27339, 27341}),
   TEARS_OF_ELIDINIS(ItemIdentification.Type.POTION, "Tears", "ToE", new int[]{27327, 27329, 27331, 27333}),
   MENAPHITE_REMEDY(ItemIdentification.Type.POTION, "MenRem", "M.R", new int[]{27202, 27205, 27208, 27211}),
   MOONLIGHT_POTION(ItemIdentification.Type.POTION, "Moon", "M", new int[]{29083, 29082, 29081, 29080}),
   GUAM_POTION(ItemIdentification.Type.POTION, "Guam", "G", new int[]{91}),
   MARRENTILL_POTION(ItemIdentification.Type.POTION, "Marren", "M", new int[]{93}),
   TARROMIN_POTION(ItemIdentification.Type.POTION, "Tarro", "TAR", new int[]{95}),
   HARRALANDER_POTION(ItemIdentification.Type.POTION, "Harra", "HAR", new int[]{97}),
   RANARR_POTION(ItemIdentification.Type.POTION, "Ranarr", "R", new int[]{99}),
   TOADFLAX_POTION(ItemIdentification.Type.POTION, "Toad", "TOA", new int[]{3002}),
   IRIT_POTION(ItemIdentification.Type.POTION, "Irit", "I", new int[]{101}),
   AVANTOE_POTION(ItemIdentification.Type.POTION, "Avan", "A", new int[]{103}),
   KWUARM_POTION(ItemIdentification.Type.POTION, "Kwuarm", "K", new int[]{105}),
   ELKHORN_POTION(ItemIdentification.Type.POTION, "Elkhorn", "ELK", new int[]{31662}),
   HAEMOSTATIC_POULTICE(ItemIdentification.Type.POTION, "Haem.P.", "HAEM", new int[]{31587}),
   PILLAR_POTION(ItemIdentification.Type.POTION, "Pillar", "PIL", new int[]{31665}),
   SNAPDRAGON_POTION(ItemIdentification.Type.POTION, "Snap", "S", new int[]{3004}),
   CADANTINE_POTION(ItemIdentification.Type.POTION, "Cadan", "C", new int[]{107}),
   LANTADYME_POTION(ItemIdentification.Type.POTION, "Lanta", "L", new int[]{2483}),
   DWARF_WEED_POTION(ItemIdentification.Type.POTION, "Dwarf", "D", new int[]{109}),
   TORSTOL_POTION(ItemIdentification.Type.POTION, "Torstol", "TOR", new int[]{111}),
   UMBRAL_POTION(ItemIdentification.Type.POTION, "Umbral", "UMB", new int[]{31668}),
   HUASCA_POTION(ItemIdentification.Type.POTION, "Huasca", "HUA", new int[]{30100}),
   BLACK_WARLOCK(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "B.War", "BW", new int[]{10014}),
   MOONLIGHT_MOTH(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Moon", "M", new int[]{28893}),
   RUBY_HARVEST(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Ruby.H", "RH", new int[]{10020}),
   SAPPHIRE_GLACIALIS(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Saph.G", "SG", new int[]{10018}),
   SNOWY_KNIGHT(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Snow.K", "SK", new int[]{10016}),
   SUNLIGHT_MOTH(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Sun", "S", new int[]{28890}),
   BLACK_WARLOCK_MIX(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "B.War x", "BW x", new int[]{29207, 29189}),
   MOONLIGHT_MOTH_MIX(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Moon x", "M x", new int[]{29213, 29195}),
   RUBY_HARVEST_MIX(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Ruby.H x", "RH x", new int[]{29204, 29186}),
   SAPPHIRE_GLACIALIS_MIX(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Saph.G x", "SG x", new int[]{29198, 29180}),
   SNOWY_KNIGHT_MIX(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Snow.K x", "SK x", new int[]{29201, 29183}),
   SUNLIGHT_MOTH_MIX(ItemIdentification.Type.BUTTERFLY_MOTH_JAR, "Sun x", "S x", new int[]{29210, 29192}),
   BABY_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Baby", "B", new int[]{11238}),
   YOUNG_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Young", "Y", new int[]{11240}),
   GOURMET_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Gourmet", "G", new int[]{11242}),
   EARTH_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Earth", "EAR", new int[]{11244}),
   ESSENCE_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Essen", "ESS", new int[]{11246}),
   ECLECTIC_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Eclect", "ECL", new int[]{11248}),
   NATURE_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Nature", "NAT", new int[]{11250}),
   MAGPIE_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Magpie", "M", new int[]{11252}),
   NINJA_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Ninja", "NIN", new int[]{11254}),
   CRYSTAL_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Crystal", "C", new int[]{23768}),
   DRAGON_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Dragon", "D", new int[]{11256}),
   LUCKY_IMPLING(ItemIdentification.Type.IMPLING_JAR, "Lucky", "L", new int[]{19732}),
   VARROCK_TELEPORT(ItemIdentification.Type.TABLET, "Varro", "VAR", new int[]{8007}),
   LUMBRIDGE_TELEPORT(ItemIdentification.Type.TABLET, "Lumbr", "LUM", new int[]{8008}),
   FALADOR_TELEPORT(ItemIdentification.Type.TABLET, "Fala", "FAL", new int[]{8009}),
   CAMELOT_TELEPORT(ItemIdentification.Type.TABLET, "Cammy", "CAM", new int[]{8010}),
   ARDOUGNE_TELEPORT(ItemIdentification.Type.TABLET, "Ardoug", "ARD", new int[]{8011}),
   WATCHTOWER_TELEPORT(ItemIdentification.Type.TABLET, "W.tow", "WT", new int[]{8012}),
   TELEPORT_TO_HOUSE(ItemIdentification.Type.TABLET, "House", "POH", new int[]{8013}),
   KOUREND_CASTLE_TELEPORT(ItemIdentification.Type.TABLET, "K.Cast", "KOU", new int[]{28790}),
   CIVITAS_ILLA_FORTIS_TELEPORT(ItemIdentification.Type.TABLET, "Civitas", "CIV", new int[]{28824}),
   ENCHANT_SAPPHIRE_OR_OPAL(ItemIdentification.Type.TABLET, "E.Saph", "E SO", new int[]{8016}),
   ENCHANT_EMERALD_OR_JADE(ItemIdentification.Type.TABLET, "E.Emer", "E EJ", new int[]{8017}),
   ENCHANT_RUBY_OR_TOPAZ(ItemIdentification.Type.TABLET, "E.Ruby", "E RT", new int[]{8018}),
   ENCHANT_DIAMOND(ItemIdentification.Type.TABLET, "E.Diam", "E DIA", new int[]{8019}),
   ENCHANT_DRAGONSTONE(ItemIdentification.Type.TABLET, "E.Dstn", "E DS", new int[]{8020}),
   ENCHANT_ONYX(ItemIdentification.Type.TABLET, "E.Onyx", "E ONX", new int[]{8021}),
   TELEKINETIC_GRAB(ItemIdentification.Type.TABLET, "T.grab", "T.GRB", new int[]{8022}),
   BONES_TO_PEACHES(ItemIdentification.Type.TABLET, "Peach", "BtP", new int[]{8015}),
   BONES_TO_BANANAS(ItemIdentification.Type.TABLET, "Banana", "BtB", new int[]{8014}),
   RIMMINGTON_TELEPORT(ItemIdentification.Type.TABLET, "Rimmi", "RIM", new int[]{11741}),
   TAVERLEY_TELEPORT(ItemIdentification.Type.TABLET, "Taver", "TAV", new int[]{11742}),
   POLLNIVNEACH_TELEPORT(ItemIdentification.Type.TABLET, "Pollnv", "POL", new int[]{11743}),
   RELLEKKA_TELEPORT(ItemIdentification.Type.TABLET, "Rell", "REL", new int[]{11744}),
   BRIMHAVEN_TELEPORT(ItemIdentification.Type.TABLET, "Brimh", "BRIM", new int[]{11745}),
   YANILLE_TELEPORT(ItemIdentification.Type.TABLET, "Yanille", "YAN", new int[]{11746}),
   TROLLHEIM_TELEPORT(ItemIdentification.Type.TABLET, "Trollh", "T.HM", new int[]{11747}),
   PRIFDDINAS_TELEPORT(ItemIdentification.Type.TABLET, "Prifd", "PRIF", new int[]{23771}),
   HOSIDIUS_TELEPORT(ItemIdentification.Type.TABLET, "Hosid", "HOS", new int[]{19651}),
   ANNAKARL_TELEPORT(ItemIdentification.Type.TABLET, "Annak", "GDZ", new int[]{12775}),
   CARRALLANGER_TELEPORT(ItemIdentification.Type.TABLET, "Carra", "CAR", new int[]{12776}),
   DAREEYAK_TELEPORT(ItemIdentification.Type.TABLET, "Dareey", "DAR", new int[]{12777}),
   GHORROCK_TELEPORT(ItemIdentification.Type.TABLET, "Ghorr", "GHRK", new int[]{12778}),
   KHARYRLL_TELEPORT(ItemIdentification.Type.TABLET, "Khary", "KHRL", new int[]{12779}),
   LASSAR_TELEPORT(ItemIdentification.Type.TABLET, "Lass", "LSR", new int[]{12780}),
   PADDEWWA_TELEPORT(ItemIdentification.Type.TABLET, "Paddew", "PDW", new int[]{12781}),
   SENNTISTEN_TELEPORT(ItemIdentification.Type.TABLET, "Sennt", "SNT", new int[]{12782}),
   ARCEUUS_LIBRARY_TELEPORT(ItemIdentification.Type.TABLET, "Arc.Lib", "A.LIB", new int[]{19613}),
   DRAYNOR_MANOR_TELEPORT(ItemIdentification.Type.TABLET, "D.Manor", "D.MNR", new int[]{19615}),
   MIND_ALTAR_TELEPORT(ItemIdentification.Type.TABLET, "M.Altar", "M.ALT", new int[]{19617}),
   SALVE_GRAVEYARD_TELEPORT(ItemIdentification.Type.TABLET, "S.Grave", "S.GRV", new int[]{19619}),
   FENKENSTRAINS_CASTLE_TELEPORT(ItemIdentification.Type.TABLET, "Fenk", "FNK", new int[]{19621}),
   WEST_ARDOUGNE_TELEPORT(ItemIdentification.Type.TABLET, "W.Ardy", "W.ARD", new int[]{19623}),
   HARMONY_ISLAND_TELEPORT(ItemIdentification.Type.TABLET, "H.Isle", "HRM", new int[]{19625}),
   CEMETERY_TELEPORT(ItemIdentification.Type.TABLET, "Cemet", "CEM", new int[]{19627}),
   BARROWS_TELEPORT(ItemIdentification.Type.TABLET, "Barrow", "BAR", new int[]{19629}),
   APE_ATOLL_TELEPORT(ItemIdentification.Type.TABLET, "Atoll", "APE", new int[]{19631}),
   BATTLEFRONT_TELEPORT(ItemIdentification.Type.TABLET, "B.Front", "BF", new int[]{22949}),
   MOONCLAN_TELEPORT(ItemIdentification.Type.TABLET, "Moon", "MOON", new int[]{24949}),
   OURANIA_TELEPORT(ItemIdentification.Type.TABLET, "Ourania", "ZMI", new int[]{24951}),
   WATERBIRTH_TELEPORT(ItemIdentification.Type.TABLET, "W.Birth", "WAT", new int[]{24953}),
   BARBARIAN_TELEPORT(ItemIdentification.Type.TABLET, "Barb", "BARB", new int[]{24955}),
   KHAZARD_TELEPORT(ItemIdentification.Type.TABLET, "Khaz", "KHA", new int[]{24957}),
   FISHING_GUILD_TELEPORT(ItemIdentification.Type.TABLET, "Fish G.", "FIS", new int[]{24959}),
   CATHERBY_TELEPORT(ItemIdentification.Type.TABLET, "Cathy", "CATH", new int[]{24961}),
   ICE_PLATEAU(ItemIdentification.Type.TABLET, "Ice Pl.", "ICE", new int[]{24963}),
   TARGET_TELEPORT(ItemIdentification.Type.TABLET, "Target", "TRG", new int[]{24336}),
   VOLCANIC_MINE_TELEPORT(ItemIdentification.Type.TABLET, "V.Mine", "VM", new int[]{21541}),
   WILDERNESS_CRABS_TELEPORT(ItemIdentification.Type.TABLET, "W.Crab", "CRAB", new int[]{24251}),
   NARDAH_TELEPORT(ItemIdentification.Type.SCROLL, "Nardah", "NAR", new int[]{12402}),
   DIGSITE_TELEPORT(ItemIdentification.Type.SCROLL, "Digsite", "DIG", new int[]{12403}),
   FELDIP_HILLS_TELEPORT(ItemIdentification.Type.SCROLL, "F.Hills", "F.H", new int[]{12404}),
   LUNAR_ISLE_TELEPORT(ItemIdentification.Type.SCROLL, "L.Isle", "L.I", new int[]{12405}),
   MORTTON_TELEPORT(ItemIdentification.Type.SCROLL, "Mort'ton", "MORT", new int[]{12406}),
   PEST_CONTROL_TELEPORT(ItemIdentification.Type.SCROLL, "P.Cont", "PEST", new int[]{12407}),
   PISCATORIS_TELEPORT(ItemIdentification.Type.SCROLL, "Pisca", "PISC", new int[]{12408}),
   TAI_BWO_WANNAI_TELEPORT(ItemIdentification.Type.SCROLL, "TaiBwo", "TAI", new int[]{12409}),
   IORWERTH_CAMP_TELEPORT(ItemIdentification.Type.SCROLL, "Iorwerth", "IOR", new int[]{12410}),
   MOS_LEHARMLESS_TELEPORT(ItemIdentification.Type.SCROLL, "M.LeHarm", "M.L", new int[]{12411}),
   LUMBERYARD_TELEPORT(ItemIdentification.Type.SCROLL, "Lumber", "LUMB", new int[]{12642}),
   ZUL_ANDRA_TELEPORT(ItemIdentification.Type.SCROLL, "Zul-andra", "ZUL", new int[]{12938}),
   KEY_MASTER_TELEPORT(ItemIdentification.Type.SCROLL, "Key master", "KEY", new int[]{13249}),
   REVENANT_CAVE_TELEPORT(ItemIdentification.Type.SCROLL, "Rev cave", "REV", new int[]{21802}),
   WATSON_TELEPORT(ItemIdentification.Type.SCROLL, "Watson", "WATS", new int[]{23387}),
   OPAL_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Opal", "OP", new int[]{21081, 21090, 21117, 21099, 21108}),
   JADE_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Jade", "J", new int[]{21084, 21093, 21120, 21102, 21111}),
   TOPAZ_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Topaz", "T", new int[]{21087, 21096, 21123, 21105, 21114}),
   GOLD_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Gold", "GOL", new int[]{1635, 1654, 11068, 1673, 1692}),
   SAPPHIRE_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Sapphir", "S", new int[]{1637, 1656, 11071, 1675, 1694}),
   EMERALD_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Emerald", "E", new int[]{1639, 1658, 11076, 1677, 1696}),
   RUBY_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Ruby", "R", new int[]{1641, 1660, 11085, 1679, 1698}),
   DIAMOND_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Diamon", "DI", new int[]{1643, 1662, 11092, 1681, 1700}),
   DRAGONSTONE_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Dragon", "DR", new int[]{1645, 1664, 11115, 1683, 1702}),
   ONYX_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Onyx", "ON", new int[]{6575, 6577, 11130, 6579, 6581}),
   ZENYTE_JEWELLERY(ItemIdentification.Type.JEWELLERY, "Zenyte", "Z", new int[]{19538, 19535, 19492, 19501, 19541}),
   RING_OF_PURSUIT(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Pursuit", "PUR", new int[]{21126}),
   DODGY_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Dodgy", "DOD", new int[]{21143}),
   EXPEDITIOUS_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Exped", "EXP", new int[]{21177}),
   AMULET_OF_BOUNTY(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Bounty", "BOU", new int[]{21160}),
   RING_OF_RETURNING(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Return", "RET", new int[]{21138, 21136, 21134, 21132, 21129}),
   NECKLACE_OF_PASSAGE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Passage", "PASS", new int[]{21155, 21153, 21151, 21149, 21146}),
   FLAMTAER_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Flamta", "FLA", new int[]{21180}),
   AMULET_OF_CHEMISTRY(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Chem", "CH", new int[]{21163}),
   EFARITAYS_AID(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Efarit", "EFA", new int[]{21140}),
   NECKLACE_OF_FAITH(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Faith", "FAI", new int[]{21157}),
   BRACELET_OF_SLAUGHTER(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Slaught", "SLA", new int[]{21183}),
   BURNING_AMULET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Burning", "BUR", new int[]{21175, 21173, 21171, 21169, 21166}),
   RING_OF_RECOIL(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Recoil", "REC", new int[]{2550}),
   GAMES_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Games", "GAME", new int[]{3867, 3865, 3863, 3861, 3859, 3857, 3855, 3853}),
   BRACELET_OF_CLAY(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Clay", "CLA", new int[]{11074}),
   AMULET_OF_MAGIC(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Magic", "MAG", new int[]{1727}),
   RING_OF_DUELING(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Duel", "DU", new int[]{2566, 2564, 2562, 2560, 2558, 2556, 2554, 2552}),
   BINDING_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Binding", "BIND", new int[]{5521}),
   CASTLE_WARS_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Castle", "CAS", new int[]{11083, 11081, 11079}),
   AMULET_OF_DEFENCE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Defence", "DEF", new int[]{1729}),
   AMULET_OF_NATURE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Nature", "NAT", new int[]{6040}),
   RING_OF_FORGING(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Forging", "FOR", new int[]{2568}),
   DIGSITE_PENDANT(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Digsite", "DIG", new int[]{11190, 11191, 11192, 11193, 11194}),
   INOCULATION_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Inocul", "INO", new int[]{11088}),
   AMULET_OF_STRENGTH(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Strengt", "STR", new int[]{1725}),
   RING_OF_LIFE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Life", "LI", new int[]{2570}),
   PHOENIX_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Phoenix", "PHO", new int[]{11090}),
   ABYSSAL_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Abyss", "ABY", new int[]{11103, 11101, 11099, 11097, 11095}),
   AMULET_OF_POWER(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Power", "POW", new int[]{1731}),
   RING_OF_WEALTH(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Wealth", "WE", new int[]{2572, 11988, 11986, 11984, 11982, 11980}),
   SKILLS_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Skill", "SK", new int[]{11113, 11111, 11109, 11107, 11105, 11970, 11968}),
   COMBAT_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Combat", "COM", new int[]{11126, 11124, 11122, 11120, 11118, 11974, 11972}),
   AMULET_OF_GLORY(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Glory", "GLO", new int[]{1704, 1706, 1708, 1710, 1712, 11976, 11978, 19707}),
   RING_OF_STONE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Stone", "STO", new int[]{6583}),
   BERSERKER_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Berserk", "BER", new int[]{11128}),
   REGEN_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Regen", "REG", new int[]{11133}),
   AMULET_OF_FURY(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Fury", "FU", new int[]{6585}),
   RING_OF_SUFFERING(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Suffer", "SUF", new int[]{19550}),
   NECKLACE_OF_ANGUISH(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Anguish", "ANG", new int[]{19547}),
   TORMENTED_BRACELET(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Torment", "TOR", new int[]{19544}),
   AMULET_OF_TORTURE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Torture", "TOR", new int[]{19553}),
   OCCULT_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Occult", "OCC", new int[]{12002}),
   DRAGONBONE_NECKLACE(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Dragon", "DRA", new int[]{22111}),
   SLAYER_RING(ItemIdentification.Type.JEWELLERY_ENCHANTED, "Slayer", "SLA", new int[]{11873, 11872, 11871, 11870, 11869, 11868, 11867, 11866, 21268}),
   JUG_OF_WATER(ItemIdentification.Type.WINES, "Water", "Wat", new int[]{1937}),
   UNFERMENTED_WINE(ItemIdentification.Type.WINES, "Unf.", "U", new int[]{1995}),
   ZAMORAKS_UNFERMENTED_WINE(ItemIdentification.Type.WINES, "Unf. Z", "UZ", new int[]{20752}),
   JUG_OF_WINE(ItemIdentification.Type.WINES, "Wine", "W", new int[]{1993}),
   WINE_OF_ZAMORAK(ItemIdentification.Type.WINES, "Zammy", "Z", new int[]{245}),
   JUG_OF_BAD_WINE(ItemIdentification.Type.WINES, "Bad", "Bad", new int[]{1991}),
   HALF_FULL_WINE_JUG(ItemIdentification.Type.WINES, "Half", "HF", new int[]{1989}),
   JUG_OF_BLESSED_WINE(ItemIdentification.Type.WINES, "Blessed", "B", new int[]{29386}),
   JUG_OF_SUNFIRE_WINE(ItemIdentification.Type.WINES, "Sunfire", "S", new int[]{29382}),
   JUG_OF_BLESSED_SUNFIRE_WINE(ItemIdentification.Type.WINES, "B. Sun", "BS", new int[]{29384});

   final Type type;
   final String medName;
   final String shortName;
   final int[] itemIDs;
   private static final Map<Integer, ItemIdentification> itemIdentifications;

   private ItemIdentification(Type type, String medName, String shortName, int... ids) {
      this.type = type;
      this.medName = medName;
      this.shortName = shortName;
      this.itemIDs = ids;
   }

   static ItemIdentification get(int id) {
      return (ItemIdentification)itemIdentifications.get(id);
   }

   static {
      ImmutableMap.Builder<Integer, ItemIdentification> builder = new ImmutableMap.Builder();
      ItemIdentification[] var1 = values();
      int var2 = var1.length;

      for(int var3 = 0; var3 < var2; ++var3) {
         ItemIdentification i = var1[var3];
         int[] var5 = i.itemIDs;
         int var6 = var5.length;

         for(int var7 = 0; var7 < var6; ++var7) {
            int id = var5[var7];
            builder.put(id, i);
         }
      }

      itemIdentifications = builder.build();
   }

   static enum Type {
      SEED_HERB(ItemIdentificationConfig::showHerbSeeds),
      SEED_BERRY(ItemIdentificationConfig::showBerrySeeds),
      SEED_ALLOTMENT(ItemIdentificationConfig::showAllotmentSeeds),
      SEED_SPECIAL(ItemIdentificationConfig::showSpecialSeeds),
      SEED_TREE(ItemIdentificationConfig::showTreeSeeds),
      SEED_FRUIT_TREE(ItemIdentificationConfig::showFruitTreeSeeds),
      SEED_FLOWER(ItemIdentificationConfig::showFlowerSeeds),
      HOPS_SEED(ItemIdentificationConfig::showHopsSeeds),
      CORAL_FRAG(ItemIdentificationConfig::showCoralFrags),
      SACK(ItemIdentificationConfig::showSacks),
      HERB(ItemIdentificationConfig::showHerbs),
      LOGS(ItemIdentificationConfig::showLogs),
      LOGS_PYRE(ItemIdentificationConfig::showPyreLogs),
      PLANK(ItemIdentificationConfig::showPlanks),
      REPAIR_KIT(ItemIdentificationConfig::showRepairKits),
      YARN(ItemIdentificationConfig::showYarn),
      CLOTH(ItemIdentificationConfig::showCloth),
      SAPLING(ItemIdentificationConfig::showSaplings),
      COMPOST(ItemIdentificationConfig::showComposts),
      ORE(ItemIdentificationConfig::showOres),
      BAR(ItemIdentificationConfig::showBars),
      GEM(ItemIdentificationConfig::showGems),
      POTION(ItemIdentificationConfig::showPotions),
      BUTTERFLY_MOTH_JAR(ItemIdentificationConfig::showButterflyMothJars),
      IMPLING_JAR(ItemIdentificationConfig::showImplingJars),
      TABLET(ItemIdentificationConfig::showTablets),
      SCROLL(ItemIdentificationConfig::showTeleportScrolls),
      JEWELLERY(ItemIdentificationConfig::showJewellery),
      JEWELLERY_ENCHANTED(ItemIdentificationConfig::showEnchantedJewellery),
      WINES(ItemIdentificationConfig::showWines);

      final Predicate<ItemIdentificationConfig> enabled;

      private Type(Predicate enabled) {
         this.enabled = enabled;
      }
   }
}
